### PR TITLE
Append semicolon to ES6 module statements

### PR DESCRIPTION
**Pull request by kewah**
Hi,

I have added the support for ES6 module statements `import` & `export`.
I have also bumped `esformatter`'s version to support ES6 syntax.

### CODE REVIEW

**Comment by bulyshko** [comment]
@kewah Thanks for your pull request. I'll take a closer look a bit later. Meanwhile, can you please make sure all tests pass.

**Comment by kewah** [comment]
Yep sorry. I have checked and it seems to be an esformatter issue (not linked to my commit):

```js
var b = '2',
  c = '3'
  ;
```

Expected (in the test):
```js
var b = '2',
  c = '3';
```

Current output:
```js
var b = '2',
  c = '3'
  ;
```

**Comment by kewah** [comment]
Issue opened on esformatter repo https://github.com/millermedeiros/esformatter/issues/334

**Comment by bulyshko** [comment]
I see. I'll work on a workaround to avoid this happening and then come back to your PR. Thanks.

**Comment by bulyshko** [comment]
I've added [workaround](https://github.com/bulyshko/esformatter-semicolons/blob/master/index.js#L21-L31) to remove white spaces and line breaks before the `;` and merged your PR. Thanks for contribution.

**Comment by kewah** [comment]
Nice :+1:

**Pull request merged**
